---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull monitthakkar/devopscalc
      
    - name: running container
      shell: sudo chmod 777 /var/run/docker.sock
      shell: docker run -it -d monitthakkar/devopscalc
